---
version: '3'
services:
  db:
    image: mariadb:10.5.8
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: root
      MYSQL_PASSWORD: Columbiabc1!
      MYSQL_DATABASE: mydb
    volumes:
      - issp_db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  app:
    depends_on:
      - db
    build: .
    environment:
      DATABASE_URL: "mysql://root:root@db:3306/mydb"
      DATABASE_URL_TESTING: "mysql://root:root@db:3306/mydb_testing"
      APP_URL: http://localhost:8000
    ports:
      - '8000:3000'
    volumes:
      - /node_modules


volumes:
  issp_db_data:
