version: 2
services:
  db:
    image: mariadb:10.5.8
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_USER: "dbuser"
      MYSQL_PASSWORD: "dbpassword"
      MYSQL_DATABASE: "dbname"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  app:
    build: .
    environment:
      DATABASE_URL: "mysql://dbuser:dbpassword@db:3306/dbname"
      APP_URL: "http://localhost:8000"
    ports:
      - "8000:3000"
    depends_on:
      - db
volumes:
  db_data:
