services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: myappdb
    ports:
      - 3306:3306
  app:
    image: node:14-alpine
    working_dir: /app
    command: npm start
    environment:
      DATABASE_URL: mysql://root:mysecretpassword@db:3306/myappdb
    ports:
      - 3000:3000
    depends_on:
      - db
