version: 2
services:
  databases:
    image: mysql:8.0
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: ptracker
      MYSQL_PASSWORD: omgverysecret
      MYSQL_DATABASE: nurse_joy
    volumes:
      - issp_db_data:/var/lib/mysql
    ports:
      - 3306:3306
  app:
    build: .
    environment:
      DATABASE_URL: "mysql://ptracker:omgverysecret@db:3306/nurse_joy"
      DATABASE_URL_TESTING: "mysql://ptracker:omgverysecret@db:3306/nurse_joy_testing"
      APP_URL: http://localhost:8000
    ports:
      - 8000:3000
    depends_on:
      - db

